project_id = "luzcecstkebntjnfonwv"

[auth]
site_url = "https://flowerproj.vercel.app"
additional_redirect_urls = [
  "https://flowerproj.vercel.app",
  "http://localhost:5173/reset-password",
  "http://127.0.0.1:5173/reset-password",
  "https://flowerproj.vercel.app/reset-password",
  "http://localhost:5173",
  "http://127.0.0.1:5173",
  "http://localhost:5173/email-verification",
  "http://127.0.0.1:5173/email-verification",
  "https://flowerproj.vercel.app/email-verification",
]

[auth.email]
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Verify your Jocerry's Flower Shop account"
content_path = "./supabase/templates/confirmation.html"

[functions.create-employee]
verify_jwt = false

[functions.confirm-email-verification]
verify_jwt = false

[functions.send-auth-verification-email]
verify_jwt = false

[functions.manage-admin-workflows]
verify_jwt = false
