import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: Platform.OS === 'android' ? 50 : 20,
    backgroundColor: '#ec4899',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#fff',
    opacity: 0.9,
  },
  content: {
    flex: 1,
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingVertical: 8,
    paddingBottom: 40,
    height: 100,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 5,
  },
  navText: {
    fontSize: 11,
    color: '#999',
    marginTop: 4,
  },
  navTextActive: {
    color: '#ec4899',
    fontWeight: '600',
  },
  navBadge: {
    position: 'absolute',
    top: -5,
    right: 20,
    backgroundColor: 'red',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  navBadgeText: {
      color: 'white',
      fontSize: 12,
      fontWeight: 'bold',
  },
  tabContent: {
    flex: 1,
    padding: 15,
  },
  tabTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#333',
  },
  addButton: {
    backgroundColor: '#ec4899',
    flexDirection: 'row',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  filterLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 5,
    color: '#333',
  },
  categoryScroll: {
    marginBottom: 20,
    maxHeight: 50, // Limit height so they don't grow too tall
  },
  categoryChip: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#e0e0e0',
    marginRight: 10,
    height: 40, // Fixed height for consistency
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryChipActive: {
    backgroundColor: '#ec4899',
  },
  categoryChipText: {
    color: '#666',
    fontSize: 14,
  },
  categoryChipTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  productCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 15,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    overflow: 'hidden', // Ensures image corners are rounded
  },
  imageContainer: {
    width: '100%',
    height: 180,
    backgroundColor: '#f8f8f8',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  productImagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
  },
  placeholderText: {
    color: '#999',
    marginTop: 5,
    fontSize: 12,
  },
  productInfo: {
    padding: 15,
  },
  productName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  productCategory: {
    fontSize: 14,
    color: '#888',
    marginBottom: 8,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  productPrice: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ec4899',
  },
    productStock: {
      fontSize: 14,
      color: '#666',
      fontWeight: '500',
    },
    inputHelperText: {
      fontSize: 12,
      color: '#666',
      marginBottom: 5,
    },
    productDescription: {
      fontSize: 12,
      color: '#777',
      marginTop: 4,
      marginBottom: 5,
    },

  unavailableBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#fee2e2',
    color: '#b91c1c',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  categoryManageRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginBottom: 12,
  },
  categoryAddBtn: {
    backgroundColor: '#ec4899',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
  },
  categoryManageItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  productActions: {
    flexDirection: 'row',
    gap: 10,
    padding: 15,
    paddingTop: 0, // Reduce top padding since info has bottom padding
  },
  editButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#3b82f6', // Blue
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  deleteButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#ef4444', // Red
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  buttonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  orderCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    alignItems: 'flex-start',
  },
  orderHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  orderDateBadge: {
    fontSize: 11,
    color: '#fff',
    backgroundColor: '#ec4899',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    fontWeight: '600',
  },
  orderNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  orderDate: {
    fontSize: 12,
    color: '#999',
  },
  orderCustomer: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
    fontWeight: '500',
  },
  orderEmail: {
    fontSize: 13,
    color: '#666',
    marginTop: 4,
  },
  orderPhone: {
    fontSize: 13,
    color: '#666',
    marginTop: 4,
  },
  orderBadges: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  badgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  orderTotal: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  changeStatusButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 8,
  },
  changeStatusText: {
    color: '#2196F3',
    fontSize: 14,
    fontWeight: '600',
  },
  stockTabs: {
    flexDirection: 'row',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  stockTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 5,
  },
  stockTabActive: {
    borderBottomWidth: 3,
    borderBottomColor: '#ec4899',
  },
  stockTabText: {
    fontSize: 14,
    color: '#666',
  },
  stockTabTextActive: {
    color: '#ec4899',
    fontWeight: '600',
  },
  stockCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 1,
  },
  stockInfo: {
    flex: 1,
  },
  stockName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  stockPrice: {
    fontSize: 14,
    color: '#ec4899',
    marginBottom: 5,
  },
  stockAvailability: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  availabilityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  stockAvailabilityText: {
    fontSize: 12,
    color: '#666',
  },
  stockActions: {
    flexDirection: 'row',
    gap: 10,
  },
  editButtonSmall: {
    padding: 8,
  },
  deleteButtonSmall: {
    padding: 8,
  },
  notificationCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    elevation: 1,
  },
  notificationContent: {
    flex: 1,
  },
  notificationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  notificationMessage: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  notificationDate: {
    fontSize: 12,
    color: '#999',
  },
  deleteIconButton: {
    padding: 5,
  },
  conversationCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 1,
  },
  avatarCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#ffe0f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  conversationContent: {
    flex: 1,
  },
  conversationName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  conversationMessage: {
    fontSize: 14,
    color: '#666',
  },
  conversationMeta: {
    alignItems: 'flex-end',
  },
  conversationDate: {
    fontSize: 12,
    color: '#999',
    marginBottom: 5,
  },
  unreadBadge: {
    backgroundColor: '#ec4899',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    minWidth: 20,
    alignItems: 'center',
  },
  unreadText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  emptyText: {
    textAlign: 'center',
    color: '#999',
    fontSize: 16,
    marginTop: 50,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    width: '90%',
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
  },
  modalCategoryChip: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  modalCategoryChipActive: {
    backgroundColor: '#ec4899',
    borderColor: '#ec4899',
  },
  modalCategoryChipText: {
    fontSize: 14,
    color: '#666',
  },
  modalCategoryChipTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  imageUploadBox: {
    height: 200,
    borderWidth: 2,
    borderColor: '#ec4899',
    borderStyle: 'dashed',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff0f5',
    marginBottom: 15,
    overflow: 'hidden',
  },
  uploadedImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  imageUploadPlaceholder: {
    alignItems: 'center',
  },
  imageUploadText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ec4899',
    marginTop: 10,
  },
  imageUploadSubtext: {
    fontSize: 12,
    color: '#666',
    marginTop: 5,
  },
  takePhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderWidth: 1,
    borderColor: '#ec4899',
    borderRadius: 8,
    marginBottom: 20,
    gap: 8,
  },
  takePhotoText: {
    color: '#ec4899',
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  notificationMessage: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  notificationDate: {
    fontSize: 12,
    color: '#999',
  },
  deleteIconButton: {
    padding: 5,
  },
  conversationCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 1,
  },
  avatarCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#ffe0f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  conversationContent: {
    flex: 1,
  },
  conversationName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  conversationMessage: {
    fontSize: 14,
    color: '#666',
  },
  conversationMeta: {
    alignItems: 'flex-end',
  },
  conversationDate: {
    fontSize: 12,
    color: '#999',
    marginBottom: 5,
  },
  unreadBadge: {
    backgroundColor: '#ec4899',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    minWidth: 20,
    alignItems: 'center',
  },
  unreadText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  emptyText: {
    textAlign: 'center',
    color: '#999',
    fontSize: 16,
    marginTop: 50,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    width: '90%',
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
  },
  modalCategoryChip: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  modalCategoryChipActive: {
    backgroundColor: '#ec4899',
    borderColor: '#ec4899',
  },
  modalCategoryChipText: {
    fontSize: 14,
    color: '#666',
  },
  modalCategoryChipTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  imageUploadBox: {
    height: 200,
    borderWidth: 2,
    borderColor: '#ec4899',
    borderStyle: 'dashed',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff0f5',
    marginBottom: 15,
    overflow: 'hidden',
  },
  uploadedImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  imageUploadPlaceholder: {
    alignItems: 'center',
  },
  imageUploadText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ec4899',
    marginTop: 10,
  },
  imageUploadSubtext: {
    fontSize: 12,
    color: '#666',
    marginTop: 5,
  },
  takePhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderWidth: 1,
    borderColor: '#ec4899',
    borderRadius: 8,
    marginBottom: 20,
    gap: 8,
  },
  takePhotoText: {
    color: '#ec4899',
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#6c757d',
  },
  saveButton: {
    backgroundColor: '#ec4899',
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-start',
  },
  menuContainer: {
    width: '70%',
    height: '100%',
    backgroundColor: '#fff',
    padding: 20,
    paddingTop: Platform.OS === 'android' ? 50 : 40,
  },
  menuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  menuTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  menuItemText: {
    fontSize: 16,
    color: '#333',
    marginLeft: 15,
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: 10,
  },
  logoutOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.52)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 28,
  },
  logoutConfirmBox: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 28,
    minWidth: 280,
    maxWidth: 340,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  logoutConfirmTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 10,
  },
  logoutConfirmMessage: {
    fontSize: 15,
    color: '#5c5c5c',
    lineHeight: 22,
    marginBottom: 28,
  },
  logoutConfirmButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  logoutCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutCancelBtnText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  logoutConfirmBtn: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: '#e53935',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutConfirmBtnText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  dropdownInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  dropdownInputText: {
    fontSize: 16,
    color: '#333',
  },
  categoryPickerItem: {
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  categoryPickerItemText: {
    fontSize: 16,
    color: '#333',
  },
  // New styles for enhanced order display
  orderTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff0f5',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    alignSelf: 'flex-start',
    marginBottom: 12,
    gap: 5,
  },
  orderTypeText: {
    color: '#ec4899',
    fontSize: 13,
    fontWeight: '600',
  },
  orderSection: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
    flex: 1,
  },
  orderPhone: {
    fontSize: 13,
    color: '#666',
    marginTop: 4,
  },
  addressContainer: {
    backgroundColor: '#f8f9fa',
    padding: 10,
    borderRadius: 8,
    marginTop: 4,
  },
  addressRecipient: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  addressPhone: {
    fontSize: 13,
    color: '#666',
    marginBottom: 6,
  },
  addressText: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  pickupText: {
    fontSize: 13,
    color: '#666',
    fontStyle: 'italic',
  },
  itemText: {
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
  },
  viewReceiptButton: {
    color: '#2196F3', // A standard blue for links/actions
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 10,
  },
  pricingSection: {
    backgroundColor: '#f8f9fa',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  priceLabel: {
    fontSize: 13,
    color: '#666',
  },
  priceValue: {
    fontSize: 13,
    color: '#333',
    fontWeight: '500',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    paddingTop: 8,
    marginTop: 4,
  },
  totalLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#333',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ec4899',
  },
  stockQuantity: {
    fontSize: 14,
    color: '#666',
  },
  switchStatusText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 10,
    fontWeight: '600',
  },
  // Sales Tab Styles
  salesSummaryContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  salesCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  salesCardValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 10,
    marginBottom: 5,
  },
  salesCardLabel: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
  },
  quickStatsContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
      sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 20,
    },  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  statLabel: {
    fontSize: 14,
    color: '#666',
  },
  statValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  statRowTotal: {
    borderBottomWidth: 0,
    borderTopWidth: 2,
    borderTopColor: '#ec4899',
    paddingTop: 12,
    marginTop: 8,
  },
  statLabelTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  statValueTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ec4899',
  },
  saleCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  saleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  saleOrderNumber: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  saleCustomer: {
    fontSize: 13,
    color: '#666',
  },
  saleRight: {
    alignItems: 'flex-end',
  },
  saleAmount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4CAF50',
    marginBottom: 5,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 11,
    color: '#fff',
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  saleDate: {
    fontSize: 12,
    color: '#999',
  },
  // Requests Tab Styles
  requestCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  requestHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  requestType: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ec4899',
  },
  requestCustomer: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  requestDate: {
    fontSize: 12,
    color: '#999',
    marginBottom: 10,
  },
  requestPreviewImageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    padding: 8,
    borderRadius: 8,
    gap: 10,
  },
  requestPreviewImage: {
    width: 40,
    height: 40,
    borderRadius: 4,
    backgroundColor: '#ddd',
  },
  viewDetailsText: {
    fontSize: 13,
    color: '#2196F3',
    fontWeight: '500',
  },
  // Messaging Tab Styles
  chatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  chatAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#ffe0f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  chatAvatarText: {
    color: '#ec4899',
    fontSize: 18,
    fontWeight: 'bold',
  },
  chatPreview: {
    flex: 1,
  },
  chatName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  chatMessage: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  chatTime: {
    fontSize: 12,
    color: '#999',
    textAlign: 'right',
  },
  chatNameUnread: {
    fontWeight: 'bold',
  },
  chatMessageUnread: {
    color: '#333',
    fontWeight: 'bold',
  },
  chatMeta: {
    alignItems: 'flex-end',
  },
  unreadBadge: {
    backgroundColor: '#ec4899',
    borderRadius: 10,
    height: 20,
    minWidth: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  unreadText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  chatHeaderTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  chatMessagesContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    backgroundColor: '#fff',
  },
  chatInput: {
    flex: 1,
    height: 40,
    backgroundColor: '#f0f2f5',
    borderRadius: 20,
    paddingHorizontal: 15,
    marginRight: 10,
    fontSize: 16,
    color: '#333',
  },
  chatSendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ec4899',
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageWrapper: {
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'flex-end',
  },
  messageSentWrapper: {
    justifyContent: 'flex-end',
  },
  messageReceivedWrapper: {
    justifyContent: 'flex-start',
  },
  messageBubble: {
    maxWidth: '75%',
    padding: 12,
    borderRadius: 18,
  },
  messageSentBubble: {
    backgroundColor: '#ec4899',
    borderBottomRightRadius: 4,
  },
  messageReceivedBubble: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 4,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  messageTextSent: {
    color: '#fff',
    fontSize: 15,
  },
  messageTextReceived: {
    color: '#333',
    fontSize: 15,
  },
  messageTime: {
    fontSize: 11,
    marginTop: 4,
    alignSelf: 'flex-end',
  },
  messageTimeSent: {
    color: '#fff',
    opacity: 0.7,
  },
  messageTimeReceived: {
    color: '#999',
  },
  messageAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#e0e0e0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  detailSection: {
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    paddingBottom: 10,
  },
  detailLabel: {
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  imageSection: {
    marginBottom: 20,
  },
  fullImage: {
    width: '100%',
    height: 300,
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
    marginBottom: 20,
  },
  actionButton: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  acceptButton: {
    backgroundColor: '#4CAF50',
  },
  rejectButton: {
    backgroundColor: '#F44336',
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  modalSubtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: '600',
  },
  radioGroup: {
    marginBottom: 20,
  },
  radioButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  radioButton: {
    height: 24,
    width: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#ddd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  radioButtonSelected: {
    borderColor: '#ec4899',
  },
  radioButtonInner: {
    height: 12,
    width: 12,
    borderRadius: 6,
    backgroundColor: '#ec4899',
  },
  radioLabel: {
    fontSize: 16,
    color: '#333',
  },
  receiptImage: { // Add this style
    width: '100%',
    height: 400, // Adjust height as needed
    backgroundColor: '#eee', // Placeholder background
  },
  riderSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f2f5',
    borderRadius: 12,
    paddingHorizontal: 10,
    marginTop: 15,
    marginBottom: 6,
  },
  riderSearchIcon: {
    marginRight: 8,
  },
  riderSearchInput: {
    flex: 1,
    height: 40,
    fontSize: 16,
    color: '#333',
  },
  riderName: {
    fontSize: 16,
    fontWeight: '600',
  },
  riderEmail: {
    fontSize: 14,
    color: '#666',
  },
  // Re-define changeStatusButton to ensure proper styling
  changeStatusButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 15,
    borderRadius: 8,
    backgroundColor: '#2196F3', // Example blue background
  },
  // Ensure changeStatusText is applied correctly
  changeStatusText: {
    color: '#fff', // White text for the blue background
    fontSize: 14,
    fontWeight: '600',
  },
  // Styles for Enhanced Orders Tab
  eoContainer: {
    flex: 1,
    backgroundColor: '#F9FAFB', // gray-50
  },
  eoTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937', // gray-800
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  eoCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginVertical: 8,
    overflow: 'hidden',
    borderLeftWidth: 4,
    borderLeftColor: '#ec4899', // pink-500
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { "width": 0, "height": 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  eoCardHeader: {
    backgroundColor: '#FEF2F7', // Lighter pink/purple mix
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: '#F3F4F6',
  },
  eoLabel: {
    fontSize: 12,
    color: '#6B7280', // gray-500
    marginBottom: 2,
  },
  eoOrderId: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  eoDateBadge: {
    backgroundColor: '#ec4899',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    marginBottom: 8,
  },
  eoDateText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  eoStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  eoStatusText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  eoProgressSection: {
    padding: 16,
    paddingTop: 8,
    backgroundColor: '#FEF2F7',
  },
  eoProgressMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  eoProgressLabel: {
    fontSize: 12,
    color: '#4B5567',
  },
  eoProgressBarBg: {
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    overflow: 'hidden',
  },
  eoProgressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  eoSection: {
    padding: 16,
    borderBottomWidth: 1,
    borderColor: '#F3F4F6',
  },
  eoCustomerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  eoAvatarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eoAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#A78BFA', // purple-400
    justifyContent: 'center',
    alignItems: 'center',
  },
  eoAvatarText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  eoCustomerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  eoActionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  eoIconBtnGreen: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#22C55E',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
  },
  eoIconBtnBlue: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#3B82F6',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
  },
  eoContactInfo: {
    gap: 8,
    marginTop: 4,
  },
  eoInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  eoInfoText: {
    fontSize: 14,
    color: '#4B5567',
    flex: 1,
  },
  eoDetailText: {
    fontSize: 14,
    color: '#4B5567',
  },
  eoInfoTextBold: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '600',
  },
  eoSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  eoSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  eoItemCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eoItemImage: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: '#FBCFE8', // pink-200
    justifyContent: 'center',
    alignItems: 'center',
  },
  eoItemName: {
    fontWeight: '500',
    color: '#1F2937',
  },
  eoItemQuantity: {
    fontSize: 12,
    color: '#6B7280',
  },
  eoItemPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: '#DB2777', // pink-600
    marginTop: 4,
  },
  eoInstructions: {
      marginTop: 12,
      backgroundColor: '#EFF6FF', // blue-50
      borderColor: '#BFDBFE', // blue-200
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
  },
  eoInstructionsTitle: {
      fontSize: 12,
      fontWeight: '600',
      color: '#1E40AF', // blue-800
      marginBottom: 4,
  },
  eoInstructionsText: {
      fontSize: 12,
      color: '#1D4ED8', // blue-700
  },
  eoFlexBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  eoPaymentStatus: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  eoPaymentStatusText: {
    color: '#fff', // Changed to white as requested
    fontSize: 12,
    fontWeight: '500',
  },
  eoViewReceipt: {
    color: '#3B82F6', // Matched with delivery badge color
    fontWeight: '600',
    fontSize: 14,
  },
  eoDivider: {
    borderTopWidth: 1,
    borderColor: '#E5E7EB',
    paddingTop: 12,
    marginTop: 12,
  },
  eoPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  eoTotalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  eoTotalValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#DB2777', // pink-600
  },
  eoFooter: {
    backgroundColor: '#F9FAFB',
    padding: 16,
  },
  eoMainBtn: {
    paddingVertical: 14,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { "width": 0, "height": 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  eoMainBtnText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  
  // New Status Modal Styles
  statusModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  statusModalContainer: {
    backgroundColor: 'white',
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { "width": 0, "height": 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
    width: '100%',
    maxWidth: 400,
    overflow: 'hidden',
  },
  statusModalHeader: {
    backgroundColor: '#8B5CF6', // purple-500
    padding: 16,
  },
  statusModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  timelineOrderNumber: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 24,
  },
  statusModalScrollView: {
    maxHeight: 400,
    padding: 16,
  },
  statusOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: '#F3F4F6',
  },
  statusOptionSelected: {
    backgroundColor: '#ec4899', // pink-500
    elevation: 4,
  },
  statusOptionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  statusModalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    borderTopWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    gap: 8,
  },
  statusConfirmButton: {
    backgroundColor: '#ec4899',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    flex: 1,
  },
  statusConfirmButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  statusCloseButton: {
    backgroundColor: '#FBCFE8', // Light pink/purple
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    flex: 1,
  },
  statusCloseButtonText: {
    color: '#374151',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // Timeline Modal Styles
  timelineModalContainer: {
    backgroundColor: '#F9FAFB', // gray-50
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
    width: '100%',
    maxWidth: 400,
    overflow: 'hidden',
  },
  timelineScrollView: {
    maxHeight: 500,
    padding: 24,
  },
  timelineStepContainer: {
    position: 'relative',
  },
  timelineStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    paddingBottom: 24,
  },
  timelineIconContainer: {
    position: 'relative',
    zIndex: 10,
    flexShrink: 0,
  },
  timelineCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E5E7EB', // gray-200
  },
  timelineCirclePast: {
    backgroundColor: '#10B981', // emerald-500
  },
  timelineCircleSelected: {
    backgroundColor: '#ec4899', // pink-500
    transform: [{ scale: 1.1 }],
    elevation: 5,
  },
  timelineCircleText: {
    color: '#6B7280',
    fontWeight: '600',
  },
  timelineLine: {
    position: 'absolute',
    left: 19.5,
    top: 40,
    bottom: -16, // Adjust to connect properly
    width: 2,
    backgroundColor: '#E5E7EB', // gray-200
  },
  timelineLineActive: {
    backgroundColor: '#F472B6', // pink-300
  },
  timelineTextContainer: {
    flex: 1,
    paddingTop: 4,
  },
  timelineLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 2,
  },
  timelineLabelPast: {
    color: '#059669', // emerald-600
  },
  timelineLabelSelected: {
    color: '#DB2777', // pink-600
  },
  timelineDescription: {
    fontSize: 14,
    color: '#6B7280',
  },
  timelineDescriptionSelected: {
    color: '#ec4899', // pink-500
  },
  timelineActions: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderColor: '#E5E7EB',
  },
  timelineCancelButton: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#FEE2E2', // red-50
  },
  timelineCancelButtonSelected: {
    backgroundColor: '#EF4444', // red-500
  },
  timelineCancelButtonText: {
    color: '#EF4444',
    fontWeight: '600',
  },
  eoDeliveryTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  eoDeliveryTypeBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  timelinePathSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  timelinePathButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
  },
  timelinePathButtonActive: {
    backgroundColor: '#3B82F6', // Default to delivery blue
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  timelinePathText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  timelinePathTextActive: {
    color: '#fff',
  },
});

export default styles;
