do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'refund_status'
      and typnamespace = 'public'::regnamespace
  ) then
    create type public.refund_status as enum (
      'requested',
      'approved',
      'gcash_submitted',
      'processing',
      'refunded',
      'rejected'
    );
  end if;
end
$$;

create table if not exists public.refund_requests (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('order', 'request')),
  order_id bigint,
  request_id bigint,
  customer_id uuid not null,
  status public.refund_status not null default 'requested',
  refund_amount numeric(10, 2) not null default 0,
  customer_reason text not null,
  admin_note text,
  rejection_reason text,
  gcash_name text,
  gcash_number text,
  refund_reference text,
  approved_by uuid,
  approved_at timestamptz,
  gcash_submitted_at timestamptz,
  processing_started_by uuid,
  processing_started_at timestamptz,
  processed_by uuid,
  processed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint refund_requests_exactly_one_target check (
    ((order_id is not null)::int + (request_id is not null)::int) = 1
  )
);

create unique index if not exists refund_requests_active_order_idx
  on public.refund_requests (order_id)
  where order_id is not null
    and status not in ('rejected'::public.refund_status, 'refunded'::public.refund_status);

create unique index if not exists refund_requests_active_request_idx
  on public.refund_requests (request_id)
  where request_id is not null
    and status not in ('rejected'::public.refund_status, 'refunded'::public.refund_status);

create index if not exists refund_requests_customer_idx
  on public.refund_requests (customer_id, created_at desc);

create index if not exists refund_requests_status_idx
  on public.refund_requests (status, created_at desc);

alter table public.refund_requests enable row level security;

create policy "Customers can view their refunds"
  on public.refund_requests
  for select
  to authenticated
  using (auth.uid() = customer_id);

create policy "Customers can update their approved refunds"
  on public.refund_requests
  for update
  to authenticated
  using (auth.uid() = customer_id)
  with check (auth.uid() = customer_id);

create policy "Staff can view and manage refunds"
  on public.refund_requests
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.users
      where users.id = auth.uid()
        and users.role in ('admin', 'employee')
    )
  )
  with check (
    exists (
      select 1
      from public.users
      where users.id = auth.uid()
        and users.role in ('admin', 'employee')
    )
  );
